name: CoCode

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: cocode-mongo
    volumes:
      - cocode-data:/data/db
    restart: always

volumes:
  cocode-data:
